### ISSUE TITLE
Update config for EuroPython 2024 Discord Server

### ISSUE THREAD

**Issue by NMertsch** [EuroPython/discord#120]
### Ticket-to-role assignments
Products in Pretix have two levels: There are *Items* like "Business" or "Personal", and each item can have multiple *Variations* like "Conference" or "Tutorial".

1. For the Discord role assignments, is it enough check the *Item* of the ticket, or can different variations lead to different role assignments?
2. Check and (if necessary) update config.toml to include all role assignments.

### Pretix URL
The Pretix URL in `config.toml` must match the event URL of EuroPython 2024.

### Discord channel/role IDs
The Channel and Role IDs in `config.toml` must match the 2024 Prod server.

**Comment by egeakman** [comment]
I think it depends on if we want to have the conference/tutorial-specific channels visible to only the respective ticket variation.
