### ISSUE TITLE
Add logging to the .log file and the channel

### ISSUE THREAD

**Issue by Cheukting** [EuroPython/discord#14]
We would like to log any error messages for troubleshooting if registration fails. In a local .log file and in a channel.

Will add that when #10 is merged

**Comment by NMertsch** [comment]
All exceptions are logged using Python's [logging](https://docs.python.org/3/library/logging.html) library. All registration attempts are logged to the Discord channel #registration-log:

![image](https://github.com/EuroPython/discord/assets/49114330/0e97b825-8307-4bf9-958d-2a9ae3c0c44e)
