### ISSUE TITLE
Cache Pretix data locally

### ISSUE THREAD

**Issue by NMertsch** [EuroPython/discord#149]
Currently, Pretix data is fetched from their API when the bot is started, and updated every 5 minutes. If we restart the bot while Pretix is down, registration will not work.

Let's cache the relevant Pretix data on the server, so registration can continue based on the last Pretix status.

**Comment by egeakman** [comment]
@NMertsch would this be a privacy/data security issue? Will it be compliant with GDPR?

Not a lawyer, so I'm not sure if I'm even asking the right questions here 😅

**Comment by NMertsch** [comment]
If a bad actor has access to the server, they will also have access to the .secrets file and thus the pretix token. Also, I was thinking of only storing the content of our "Ticket" objects and not the full Pretix data: Order ID, Name, Ticket Type.

**Comment by egeakman** [comment]
> Also, I was thinking of only storing the content of our "Ticket" objects and not the full Pretix data: Order ID, Name, Ticket Type. That's also what will be printed on the badges.

Yeah this makes sense, thank you!
